apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
          - name: mysql-port
            containerPort: 3306
          env:
          - name: MYSQL_DATABASE
            value: "mysql+pymysql://root:pass@mysql:3306/db"
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - ports:
            - containerPort: 5000    


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: georgerhodes/fund-pro
          ports:
          - name: app-port
            containerPort: 5000
          env:
          - name: DATABASE_URI
            value: "sqlite:///"
          - name: SECRET_KEY
            value: ""
  

---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
#  selector:
#    app: mysql
#  ports:
#  - protocol: TCP
#    port: 3306
#    targetPort: 3306
#  type: ClusterIP