apiVersion: v1
kind: Service
metadata:
  name: exercise-tracker
spec:
  selector:
    app: exercise-tracker
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  labels: 
    app: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: georgerhodes/service-1
        env:
        - name: DB_URI 
          value: "mysql+pymysql://root:passw@mysql-db:3306/dbb"
        - name: SECRET_KEY
          value: "passw"
        ports:
        - containerPort: 5000