apiVersion: v1
kind: Service
metadata:
  name: service-4
spec:
  selector:
    app: service-4
  ports: 
  - protocol: TCP
    port: 5003
    targetPort: 5003

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-4
  labels: 
    app: service-4
spec:
  selector:
    matchLabels:
      app: service-4
  template:
    metadata:
      labels:
        app: service-4
    spec:
      containers:
      - name: service-4
        image: georgerhodes/service-4
        ports:
        - containerPort: 5003