apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passw"
        - name: MYSQL_DATABASE 
          value: "dbb"
        ports:
        - containerPort: 3306

---


apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql-db
  selector:
    app: mysql-db




